services:
  - type: web
    name: krypton-hub
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && npm install && npm run build && python manage.py collectstatic --noinput && python manage.py migrate && python populate_db.py"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
