# Generated by Django 5.2.16 on 2026-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(
                    help_text="Lucide icon name (e.g. 'code-2', 'shield-check')", max_length=100)),
                ('color_theme', models.CharField(
                    help_text="Tailwind color prefix (e.g. 'accent', 'success', 'orange-400', 'purple-400')", max_length=50)),
                ('order', models.PositiveIntegerField(
                    default=0, help_text='Order in which service appears')),
                ('features', models.TextField(blank=True,
                 help_text='Enter features separated by a new line')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(
                    help_text="e.g. 'Advanced Engineering', 'Defensive Architecture'", max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(
                    help_text='Upload 1:1 ratio square WebP image', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
